### ISSUE TITLE
cancelPurchase

### ISSUE THREAD

**Issue by ameer017** [EarthFi/Earthfi#33]
Purpose: Allows a buyer to cancel the purchase if the asset is not received within an agreed time frame.
Explanation: In cases where delivery fails, this function enables the buyer to cancel the transaction and reclaim the funds held in escrow. It requires verification of the buyer’s claim and potentially a timeout period before funds are released.

**Comment by Kenny001-spec** [comment]
I'll work on implementing the cancelPurchase features.
