### ISSUE TITLE
getUserAssets

### ISSUE THREAD

**Issue by ameer017** [EarthFi/Earthfi#36]
Purpose: Retrieves details of all assets bought or sold by a specific user.
Explanation: This function takes the user’s address as input and checks the contract records to find assets either bought or sold by that address. It returns an array containing each asset’s details (such as asset ID, price, transaction status, and timestamps). This allows users to view their transaction history on their profile page, displaying both purchased assets and any assets they’ve listed and sold.

**Comment by Kenny001-spec** [comment]
i'll work on this issue of getUserAssets
